services:
  nginx:
    container_name: reverse-nginx
    restart: always
    build:
      context: ./src/requirements/nginx
    ports:
      - "8080:443"
    env_file:
      - ./src/.env
    networks:
      - my-network

  focalboard:
    container_name: focalboard
    restart: always
    build:
      context: ./src/requirements/focalboard
    ports:
      - "8000"
    env_file:
      - ./src/.env
    volumes:
      - focalboard-data:/var/lib/focalboard/data
    networks:
      - my-network

  postgresql:
    container_name: postgresql
    restart: always
    build:
      context: ./src/requirements/postgresql
    ports:
      - "5432"
    env_file:
      - ./src/.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgresql-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/postgresql
      o: bind

  focalboard-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/focalboard
      o: bind

