services:
  nginx:
    container_name: reverse-nginx
    restart: always
    build:
      context: ./src/requirements/nginx
    ports:
      - "443:443"
    env_file:
      - ./src/.env
    networks:
      - my-network

  focalboard:
    container_name: focalboard
    restart: always
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    build:
      context: ./src/requirements/focalboard
    env_file:
      - ./src/.env
    volumes:
      - focalboard-data:/var/lib/focalboard/data
    secrets:
      - db_credentials
    networks:
      - my-network

  postgresql:
    container_name: postgresql
    restart: always
    build:
      context: ./src/requirements/postgresql
    env_file:
      - ./src/.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    secrets:
      - db_credentials
    networks:
      - my-network
  

networks:
  my-network:

volumes:
  postgresql-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usb/data/postgresql
      o: bind

  focalboard-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usb/data/focalboard
      o: bind

secrets:
  db_credentials:
    file: ./secrets/postgres_credentials.txt
